config/routes.rb
Rails.application.routes.draw do
  root "items#index"


  get 'purchase/index'
  get 'purchase/done'
  get 'cards/card'
  get 'home/show'
  get 'cards/editpro'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'telephones', to: 'users/registrations#new_telephones'
    post 'telephones', to: 'users/registrations#create_telephone'
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'users/signup' => 'users/registrations#new_sns', as:"new0_user_registration"
  end
  
  # omniauthのテスト用
  # get "auth/:provider" => "authentications#new", as: :new_authentication
  # get "auth/:provider/callback" => "authentications#create", as: :create_authentication


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'cards/index'
  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  
  resources :items do
    member do
      get 'buy'
      post 'buy_create'
      post 'pay'
      get 'done'
    end
    collection do
      get 'search'
    end
  end
  resources :brands, only: [:index, :new, :show]
  resources :categories, only:[:index]
  resources :images 

  resources :purchase, only: [:index] do
    collection do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
    member do
      get 'index', to: 'purchase#index'
    end
    
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def show
  end

  def new
  end

  def index
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer2.html.haml
%footer.add-item__footer
  .add-item__footer__list
    %ul.add-item__footer__list--ul
      %li.add-item__footer__list--ul--li プライバシーポリシー
      %li.add-item__footer__list--ul--li メルカリ利用規約
      %li.add-item__footer__list--ul--li 特定商取引に関する表記
  = link_to items_path, class: "add-item__footer__logo" do
    %h3.add-item__footer__text
  © Mercari, Inc.

app/views/home/_header.html.haml
.myheader
  .mybox
    .myboxtop
      .myboxtop__img
        = image_tag "fmarket_logo_red.svg", class: "myboxtop__img", alt:"logo"
      .myboxtop__form
        %input#keyword.boxtop__form{:placeholder => "何かお探しですか？", :type => "text"}/
        = link_to "#", class: "myboxtop__form" do
          = icon('fas', 'search', class: 'myboxtop__form--icon')
    .myboxbar
      .myboxbar__list
        = link_to "#", class: "myboxbar__list" do
          = icon('fas', 'list-ul', class: 'myboxbar__list--icon')
          カテゴリーから探す
        = link_to "#", class: "myboxbar__list" do
          = icon('fas', 'tags', class: 'myboxbar__list--icon')
          ブランドから探す
      %ul.myboxbar_end
        %li.myboxbar_end--li
          = link_to "#", class: "myboxbar_end--li" do
            = icon('far', 'heart', class: 'myboxbar_end--li--icon')
            いいね！一覧
        %li.myboxbar_end--li
          = link_to "#", class: "myboxbar_end--li" do
            = icon('far', 'bell', class: 'myboxbar_end--li--icon')
            お知らせ
        %li.myboxbar_end--li
          = link_to "#", class: "myboxbar_end--li" do
            = icon('fas', 'check', class: 'myboxbar_end--li--icon')
            やることリスト
        %li.myboxbar_end--li
          = link_to cards_index_path, class: "myboxbar_end--li" do
            マイページ
.mybox-bottom
  %ul.menulist
    %li.menulist__sub
    - breadcrumb :information
    = render "layouts/breadcrumbs"

app/views/home/_logo-header.html.haml
.myheader{style: 'background: #f5f5f5; box-shadow: none;'}
  .mybox
    .myboxtop
    = link_to items_path, class: "menulist__sub" do
      .myboxtop__img{style: 'margin: 0 auto;'}
        = image_tag "fmarket_logo_red.svg", class: "myboxtop__img", alt:"logo"

app/views/home/_main.html.haml
.mymain

  .mycategory
    .sub-bar
      .sub-bar__list
        %ul.sub-bar__list__mypage1
          %li.sub-bar__list__mypage1--top
            = link_to cards_index_path, class: "sub-bar__list__mypage1--top" do
              #text
                マイページ
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--top--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                お知らせ
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                やることリスト
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                いいね！一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品する
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品した商品-出品中
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品した商品-取引中
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品した商品-売却済み
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                購入した商品-取引中
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                購入した商品-過去の取引
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                ニュース一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                評価一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                ガイド
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                お問い合わせ
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
        %ul.sub-bar__list__mypage2
          %li.sub-bar__list__mypage2--second
            #text
              Fペイ
          %li.sub-bar__list__mypage2--box2
            = link_to "#", class: "sub-bar__list__mypage2--box2" do
              #text
                売上・振込一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage2--box2--icon')
          %li.sub-bar__list__mypage2--box2
            = link_to "#", class: "sub-bar__list__mypage2--box2" do
              #text
                ポイント
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage2--box2--icon')
        %ul.sub-bar__list__mypage3
          %li.sub-bar__list__mypage3--third
            #text
              設定
          %li.sub-bar__list__mypage3--box3
            = link_to new_card_path, class: "sub-bar__list__mypage3--box3" do
              #text
                プロフィール
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                発送元・お届け先住所変更
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to cards_card_path, class: "sub-bar__list__mypage3--box3" do
              #text
                支払い方法変更
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                メール/パスワード
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to home_show_path, class: "sub-bar__list__mypage3--box3" do
              #text
                本人情報
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                電話番号の確認
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to images_path, class: "sub-bar__list__mypage3--box3" do
              #text
                ログアウト
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')

app/views/home/_newheader.html.haml
.myheader
  .mybox
    .myboxtop
      .myboxtop__img
        = image_tag "fmarket_logo_red.svg", class: "myboxtop__img", alt:"logo"
      .myboxtop__form
        %input#keyword.boxtop__form{:placeholder => "何かお探しですか？", :type => "text"}/
        = link_to "#", class: "myboxtop__form" do
          = icon('fas', 'search', class: 'myboxtop__form--icon')
    .myboxbar
      .myboxbar__list
        = link_to "#", class: "myboxbar__list" do
          = icon('fas', 'list-ul', class: 'myboxbar__list--icon')
          カテゴリーから探す
        = link_to "#", class: "myboxbar__list" do
          = icon('fas', 'tags', class: 'myboxbar__list--icon')
          ブランドから探す
      %ul.myboxbar_end
        %li.myboxbar_end--li
          = link_to "#", class: "myboxbar_end--li" do
            = icon('far', 'heart', class: 'myboxbar_end--li--icon')
            いいね！一覧
        %li.myboxbar_end--li
          = link_to "#", class: "myboxbar_end--li" do
            = icon('far', 'bell', class: 'myboxbar_end--li--icon')
            お知らせ
        %li.myboxbar_end--li
          = link_to "#", class: "myboxbar_end--li" do
            = icon('fas', 'check', class: 'myboxbar_end--li--icon')
            やることリスト
        %li.myboxbar_end--li
          = link_to cards_index_path, class: "myboxbar_end--li" do
            マイページ

.mybox-bottom
  %ul.menulist
    %li.menulist__sub
      = link_to root_path, class: "menulist__sub" do
        %span
          Fmarket
        = icon('fas', 'chevron-right', class: 'menulist__sub--icon')
      = link_to cards_path, class: "menulist__sub" do
        %span
          マイページ
        = icon('fas', 'chevron-right', class: 'menulist__sub--icon')
        %span.now
          プロフィール

app/views/home/_newmain.html.haml
.mymain

  .mycategory
    .sub-bar
      .sub-bar__list
        %ul.sub-bar__list__mypage1
          %li.sub-bar__list__mypage1--box1
            = link_to cards_index_path, class: "sub-bar__list__mypage1--box1" do
              #text
                マイページ
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                お知らせ
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                やることリスト
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                いいね！一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to new_item_path, class: "sub-bar__list__mypage1--box1" do
              #text
                出品する
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品した商品-出品中
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品した商品-取引中
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品した商品-売却済み
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                購入した商品-取引中
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                購入した商品-過去の取引
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                ニュース一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                評価一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                ガイド
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                お問い合わせ
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
        %ul.sub-bar__list__mypage2
          %li.sub-bar__list__mypage2--second
            #text
              Fペイ
          %li.sub-bar__list__mypage2--box2
            = link_to "#", class: "sub-bar__list__mypage2--box2" do
              #text
                売上・振込一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage2--box2--icon')
          %li.sub-bar__list__mypage2--box2
            = link_to "#", class: "sub-bar__list__mypage2--box2" do
              #text
                ポイント
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage2--box2--icon')
        %ul.sub-bar__list__mypage3
          %li.sub-bar__list__mypage3--third
            #text
              設定
          %li.sub-bar__list__mypage1--top
            = link_to "#", class: "sub-bar__list__mypage1--top" do
              #text
                プロフィール
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--top--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                発送元・お届け先住所変更
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                支払い方法変更
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                メール/パスワード
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                本人情報
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                電話番号の確認
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to images_path, class: "sub-bar__list__mypage3--box3" do
              #text
                ログアウト
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')

      %section.chapter-container.mypageidentification
        %h2.chapter-head
          本人情報の登録
        .single-innner
        = form_for '' do |f|
          .box
            %p お客さまの本人情報をご登録ください。
            %br
            登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
            %p.text-right
              %a 本人確認書類のアップロードについて
              %i.fas.fa-angle-right
              
          .form-group
            %label お名前
            %p 新井　達也
          .form-group
            %label お名前カナ
            %p アライ　タツヤ
          .form-group
            %label 生年月日
            %p 1987/03/25
          .form-group
            = f.label :郵便番号
            %span.form-arbitray 任意
            = f.text_field :zip_code, placeholder: "例）1234567", class: "input-default"
          .form-group
            = f.label :都道府県
            %span.form-arbitray 任意
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "--", class: "input-default"
            %i.fas.fa-angle-bottom

          .form-group
            = f.label :市区町村
            %span.form-arbitray 任意
            = f.string_field :city, placeholder: "横浜市緑区", class: "input-default"
          .form-group
            = f.label :番地
            %span.form-arbitray 任意
            = f.string_field :town, placeholder: "例）１２−３", class: "input-default"
          .form-group
            = f.label :建物
            %span.form-arbitray 任意
            = f.string_field :building, placeholder: "例）青山ビル", class: "input-default"
          .actions
            = f.submit "登録する", class: "btn-gradient-3d" 
          .form-group
          %p.text-right
            %a 本人情報の登録について
            %i.fas.fa-angle-right

app/views/home/_sell.html.haml
.sell
  .sell__btn
    = link_to "#", class: "sell__btn" do
      %p
        出品
      = icon('fas', 'camera', class: 'sell__btn--icon')

app/views/home/_showmain.html.haml
.mymain

  .mycategory
    .sub-bar
      .sub-bar__list
        %ul.sub-bar__list__mypage1
          %li.sub-bar__list__mypage1--top
            = link_to "#", class: "sub-bar__list__mypage1--top" do
              #text
                マイページ
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--top--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                お知らせ
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                やることリスト
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                いいね！一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to new_brand_path, class: "sub-bar__list__mypage1--box1" do
              #text
                出品する
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品した商品-出品中
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品した商品-取引中
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品した商品-売却済み
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                購入した商品-取引中
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                購入した商品-過去の取引
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                ニュース一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                評価一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                ガイド
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                お問い合わせ
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
        %ul.sub-bar__list__mypage2
          %li.sub-bar__list__mypage2--second
            #text
              Fペイ
          %li.sub-bar__list__mypage2--box2
            = link_to "#", class: "sub-bar__list__mypage2--box2" do
              #text
                売上・振込一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage2--box2--icon')
          %li.sub-bar__list__mypage2--box2
            = link_to "#", class: "sub-bar__list__mypage2--box2" do
              #text
                ポイント
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage2--box2--icon')
        %ul.sub-bar__list__mypage3
          %li.sub-bar__list__mypage3--third
            #text
              設定
          %li.sub-bar__list__mypage3--box3
            = link_to new_card_path, class: "sub-bar__list__mypage3--box3" do
              #text
                プロフィール
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                発送元・お届け先住所変更
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to cards_card_path, class: "sub-bar__list__mypage3--box3" do
              #text
                支払い方法変更
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                メール/パスワード
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to home_show_path, class: "sub-bar__list__mypage3--box3" do
              #text
                本人情報
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                電話番号の確認
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to images_path, class: "sub-bar__list__mypage3--box3" do
              #text
                ログアウト
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')


    .wrapper
      .contenthome
        .chapter-container.mypageidentification
          %h2.chapter-head
            本人情報の登録
          .single-innner
          = form_for '' do |f|
            .box
              %p お客さまの本人情報をご登録ください。
              %br
              登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
              .text-right
              = link_to "#", class: "bar--right" do
                本人確認書類のアップロードについて
                %i.fas.fa-angle-right
                
            .form-group
              %label お名前
              %p 新井　達也
            .form-group
              %label お名前カナ
              %p アライタツヤ
            .form-group
              %label 生年月日
              %p 1987/03/25
            .form-group
              = f.label :郵便番号
              %span.form-arbitray 任意
              = f.text_field :zip_code, placeholder: "例）1234567", type: "text", value: "", class: "input-default"
            .form-group
              = f.label :都道府県
              %span.form-arbitray 任意
              = f.collection_select :prefecture_id, Prefecture.all, :id, :name, prompt: "--"
              %i.fas.fa-angle-bottom

            .form-group
              = f.label :市区町村
              %span.form-arbitray 任意
              = f.text_field :city, placeholder: "横浜市緑区", class: "input-default"
            .form-group
              = f.label :番地
              %span.form-arbitray 任意
              = f.text_field :town, placeholder: "例）青山1-1-1", class: "input-default"
            .form-group
              = f.label :建物
              %span.form-arbitray 任意
              = f.text_field :building, placeholder: "例）青山ビル", class: "input-default"
            .actions
              = f.submit "登録する", class: "btn-gradient-3d" 
            .form-group
            = link_to "#", class: "bar--right" do
              本人情報の登録について>
              %i.fas.fa-angle-rightt

app/views/home/index.html.haml
.wrapper
  = render "newheader"
  = render "newmain"
  = render "sell"
  = render "footer"

app/views/home/show.html.haml
.wrapper
  = render "header"
  = render "showmain"
  = render "cards/footer"