config/routes.rb
Rails.application.routes.draw do
  root "items#index"


  get 'purchase/index'
  get 'purchase/done'
  get 'cards/card'
  get 'home/show'
  get 'cards/editpro'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'telephones', to: 'users/registrations#new_telephones'
    post 'telephones', to: 'users/registrations#create_telephone'
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'users/signup' => 'users/registrations#new_sns', as:"new0_user_registration"
  end
  
  # omniauthのテスト用
  # get "auth/:provider" => "authentications#new", as: :new_authentication
  # get "auth/:provider/callback" => "authentications#create", as: :create_authentication


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'cards/index'
  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  
  resources :items do
    member do
      get 'buy'
      post 'buy_create'
      post 'pay'
      get 'done'
    end
    collection do
      get 'search'
    end
  end
  resources :brands, only: [:index, :new, :show]
  resources :categories, only:[:index]
  resources :images 

  resources :purchase, only: [:index] do
    collection do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
    member do
      get 'index', to: 'purchase#index'
    end
    
  end

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
 class CardsController < ApplicationController
   require "payjp"
   before_action :set_card, only:[:new,:show,:delete]

   def index

   end
  
   def new
     redirect_to action: "show" if @card.present?
   end

   def pay #payjpとCardのデータベース作成を実施します。
     Payjp.api_key = Rails.application.credentials[:pay_jp][:PAYJP_PRIVATE_KEY]
     if params['payjp-token'].blank?
       redirect_to action: "new"
     else
       customer = Payjp::Customer.create(
       description: '登録テスト',  
       card: params['payjp-token'],
       metadata: {user_id: current_user.id}
       ) 
       @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
       if @card.save
         redirect_to action: "show"
       else
         redirect_to action: "pay"
       end
     end
   end

   def delete #PayjpとCardデータベースを削除します
     if @card.blank?
     else
       Payjp.api_key = Rails.application.credentials[:pay_jp][:PAYJP_PRIVATE_KEY]
       customer = Payjp::Customer.retrieve(@card.customer_id)
       customer.delete
       @card.delete
     end
       redirect_to action: "new"
   end

   def show #Cardのデータpayjpに送り情報を取り出します
     if @card.blank?
       redirect_to action: "new" 
     else
       Payjp.api_key = Rails.application.credentials[:pay_jp][:PAYJP_PRIVATE_KEY]
       customer = Payjp::Customer.retrieve(@card.customer_id)
       @default_card_information = customer.cards.retrieve(@card.card_id)
     end
   end

   def edit
   end
  
   private

   def set_card
     @card = Card.find_by(user_id: current_user.id) 
   end

 end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card2.html.haml
    .container
      .content
        %section.content__chapter
          %h2.chapter__head 支払い方法
          .chapter__inner
            %section
              .chapter__inner__title
                %h3.chapter__inner__title__text クレジットカード一覧
              .chapter__inner__setting-card
                %ul.chapter__inner__setting-card__list
                  %li
                    %form
                      %figure
                        = image_tag "Mastercard-logo.svg",width:"28px",height:"20px", alt:"masca"
                      .chapter__inner__setting-card__list__payment_number
                        ************2303
                      .chapter__inner__setting-card__list__payment_day
                        09 / 24
                      %button.settings-payment-remove
                        削除する
            .setting-not-resist
              = link_to "#", class: ".setting-not-resist" do
                %span 支払い方法について
                %i.fas.fa-angle-right

app/views/cards/_header.html.haml
.myheader
  .mybox
    .myboxtop
      
      = link_to root_path, class: "" do
        = image_tag "fmarket_logo_red.svg", class: "myboxtop__img", alt:"logo"
      .myboxtop__form
        = form_with(url: search_items_path, local: true, method: :get, id: "keyword") do |form| 
          = form.text_field :keyword, placeholder: "何かお探しですか？", class: "myboxtop__form" 
          = button_tag type: "submit", class: "myboxtop__form--icon" do
            %i.fa.fa-search
        %end
    .myboxbar
      .myboxbar__list
        = link_to "#", class: "myboxbar__list" do
          = icon('fas', 'list-ul', class: 'myboxbar__list--icon')
          カテゴリーから探す
        = link_to brands_path, class: "myboxbar__list" do
          = icon('fas', 'tags', class: 'myboxbar__list--icon')
          ブランドから探す
      %ul.myboxbar_end
        %li.myboxbar_end--li
          = link_to "#", class: "myboxbar_end--li" do
            = icon('far', 'heart', class: 'myboxbar_end--li--icon')
            いいね！一覧
        %li.myboxbar_end--li
          = link_to "#", class: "myboxbar_end--li" do
            = icon('far', 'bell', class: 'myboxbar_end--li--icon')
            お知らせ
        %li.myboxbar_end--li
          = link_to "#", class: "myboxbar_end--li" do
            = icon('fas', 'check', class: 'myboxbar_end--li--icon')
            やることリスト
        %li.myboxbar_end--myli
          = link_to cards_index_path, class: "myboxbar_end--myli" do
            .myboxbar_end--myli--img
            マイページ
.mybox-bottom
  %ul.menulist
    %li.menulist__sub
    - breadcrumb :mypage
    = render "layouts/breadcrumbs"

app/views/cards/_main.html.haml
.mymain

  .mycategory
    .sub-bar
      .sub-bar__list
        %ul.sub-bar__list__mypage1
          %li.sub-bar__list__mypage1--top
            = link_to "#", class: "sub-bar__list__mypage1--top" do
              #text
                マイページ
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--top--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                お知らせ
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                やることリスト
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                いいね！一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to new_brand_path, class: "sub-bar__list__mypage1--box1" do
              #text
                出品する
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品した商品-出品中
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品した商品-取引中
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品した商品-売却済み
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                購入した商品-取引中
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                購入した商品-過去の取引
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                ニュース一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                評価一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                ガイド
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                お問い合わせ
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
        %ul.sub-bar__list__mypage2
          %li.sub-bar__list__mypage2--second
            #text
              Fペイ
          %li.sub-bar__list__mypage2--box2
            = link_to "#", class: "sub-bar__list__mypage2--box2" do
              #text
                売上・振込一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage2--box2--icon')
          %li.sub-bar__list__mypage2--box2
            = link_to "#", class: "sub-bar__list__mypage2--box2" do
              #text
                ポイント
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage2--box2--icon')
        %ul.sub-bar__list__mypage3
          %li.sub-bar__list__mypage3--third
            #text
              設定
          %li.sub-bar__list__mypage3--box3
            = link_to cards_editpro_path, class: "sub-bar__list__mypage3--box3" do
              #text
                プロフィール
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                発送元・お届け先住所変更
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to cards_card_path, class: "sub-bar__list__mypage3--box3" do
              #text
                支払い方法変更
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                メール/パスワード
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to home_show_path, class: "sub-bar__list__mypage3--box3" do
              #text
                本人情報
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                電話番号の確認
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to images_path, class: "sub-bar__list__mypage3--box3" do
              #text
                ログアウト
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')



    .container
      .content
        .content__top
          .userimage
            = link_to "#", class: "myimg" do
              .topimg
              %h2.myname
                = current_user.name
              .bottomimg
                評価　　　出品数
                
        .contentbox
          .content__todo
            .content__todo__tabs
              %input#tableft1{class: "tabswitch", checked: "checkedleft1", name: "content__todo__tabs__title", type: "radio"}
              %label.content__todo__tabs__title{for: "tableft1"}
                %h1 お知らせ
              %input#tabright1{class: "tabswitch", checked: "checkedright1", name: "content__todo__tabs__title", type: "radio"}
              %label.content__todo__tabs__title{for: "tabright1"} 
                %h1 やることリスト
            .content__todo__content
              %ul.content__todo__content__list
                %li#tableft1_content.content__todo__content__list__tag
                  = link_to "#", class: "" do
                    = image_tag "logo_red.svg", class: "", alt:"logo"
                    .content__todo__content__list__tag__box
                      .content__todo__content__list__tag__box__write
                        ポイントチャンス！！！
                      %time
                        ６時間前
                    = icon('fas', 'chevron-right', class: 'content__todo__content__list__tag--icon')
                %li#tableft1_content.content__todo__content__list__sum
                  = link_to "#", class: "" do
                    一覧を見る

                %li#tabright1_content.content__todo__content__list__tag
                  -# 何もありません




        .content__tab-container
          .content__tab-container__top
            %h1 購入した商品
          .content__tab-container__box
            .content__tab-container__box__tabs
              %input#tableft2{class: "tab-switch", checked: "checked" ,name: "content__tab-container__box__tabs__title", type: "radio"}
              %label.content__tab-container__box__tabs__title{for: "tableft2", checked: "checked"}
                %h1 取引中
              %input#tabright2{class: "tab-switch", name: "content__tab-container__box__tabs__title", type: "radio"}
              %label.content__tab-container__box__tabs__title{for: "tabright2"} 
                %h1 過去の取引
            .content__tab-container__box__content
              #tableft2_content.content__tab-container__box__content
                取引中のものはありません
              #tabright2_content.content__tab-container__box__content
                過去の取引はありません

app/views/cards/_newheader.html.haml
.myheader
  .mybox
    .myboxtop
      = link_to root_path, class: "" do
        = image_tag "fmarket_logo_red.svg", class: "myboxtop__newimg", alt:"logo"
      .myboxtop__form
        %input#keyword.boxtop__form{:placeholder => "何かお探しですか？", :type => "text"}/
        = link_to "#", class: "myboxtop__form" do
          = icon('fas', 'search', class: 'myboxtop__form--icon')
    .myboxbar
      .myboxbar__list
        = link_to "#", class: "myboxbar__list" do
          = icon('fas', 'list-ul', class: 'myboxbar__list--icon')
          カテゴリーから探す
        = link_to brands_path, class: "myboxbar__list" do
          = icon('fas', 'tags', class: 'myboxbar__list--icon')
          ブランドから探す
      %ul.myboxbar_end
        %li.myboxbar_end--li
          = link_to "#", class: "myboxbar_end--li" do
            = icon('far', 'heart', class: 'myboxbar_end--li--icon')
            いいね！一覧
        %li.myboxbar_end--li
          = link_to "#", class: "myboxbar_end--li" do
            = icon('far', 'bell', class: 'myboxbar_end--li--icon')
            お知らせ
        %li.myboxbar_end--li
          = link_to "#", class: "myboxbar_end--li" do
            = icon('fas', 'check', class: 'myboxbar_end--li--icon')
            やることリスト
        %li.myboxbar_end--myli
          = link_to cards_index_path, class: "myboxbar_end--myli" do
            .myboxbar_end--myli--img
            マイページ

.mybox-bottom
  %ul.menulist
    %li.menulist__sub
    - breadcrumb :profile
    = render "layouts/breadcrumbs"

app/views/cards/_newmain.html.haml
.mymain

  .mycategory
    .sub-bar
      .sub-bar__list
        %ul.sub-bar__list__mypage1
          %li.sub-bar__list__mypage1--box1
            = link_to cards_index_path, class: "sub-bar__list__mypage1--box1" do
              #text
                マイページ
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                お知らせ
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                やることリスト
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                いいね！一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品する
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品した商品-出品中
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品した商品-取引中
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                出品した商品-売却済み
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                購入した商品-取引中
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                購入した商品-過去の取引
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                ニュース一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                評価一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                ガイド
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
          %li.sub-bar__list__mypage1--box1
            = link_to "#", class: "sub-bar__list__mypage1--box1" do
              #text
                お問い合わせ
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--box1--icon')
        %ul.sub-bar__list__mypage2
          %li.sub-bar__list__mypage2--second
            #text
              Fペイ
          %li.sub-bar__list__mypage2--box2
            = link_to "#", class: "sub-bar__list__mypage2--box2" do
              #text
                売上・振込一覧
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage2--box2--icon')
          %li.sub-bar__list__mypage2--box2
            = link_to "#", class: "sub-bar__list__mypage2--box2" do
              #text
                ポイント
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage2--box2--icon')
        %ul.sub-bar__list__mypage3
          %li.sub-bar__list__mypage3--third
            #text
              設定
          %li.sub-bar__list__mypage1--top
            = link_to "#", class: "sub-bar__list__mypage1--top" do
              #text
                プロフィール
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage1--top--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                発送元・お届け先住所変更
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to cards_card_path, class: "sub-bar__list__mypage3--box3" do
              #text
                支払い方法変更
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                メール/パスワード
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to home_show_path, class: "sub-bar__list__mypage3--box3" do
              #text
                本人情報
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to "#", class: "sub-bar__list__mypage3--box3" do
              #text
                電話番号の確認
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')
          %li.sub-bar__list__mypage3--box3
            = link_to images_path, class: "sub-bar__list__mypage3--box3" do
              #text
                ログアウト
              = icon('fas', 'chevron-right', class: 'sub-bar__list__mypage3--box3--icon')



    .container
      %h2.toptitle
        プロフィール
      .content
        .content__top
          .userimage
            .myimg
              .myimg__top
              %input#keyword.myimg__form{placeholder: "" , type: "text"}
 
        .content__prof
          %textarea.content__prof__text{name: "content", placeholder: "例）こんにちは! ご覧頂きありがとうございます!", type: "text"}

          .content__prof__sum
            = link_to "#", class: "" do
              変更する

app/views/cards/_smallfooter.html.haml
%footer.add-item__footer
  .add-item__footer__list
    %ul.add-item__footer__list--ul
      %li.add-item__footer__list--ul--li プライバシーポリシー
      %li.add-item__footer__list--ul--li メルカリ利用規約
      %li.add-item__footer__list--ul--li 特定商取引に関する表記
  %a.add-item__footer__logo{:href => "#"}
  .add-item__footer__text
    © Fmarket, Inc.

app/views/cards/card.html.haml
.wrapper
  = render "home/header2"
  = render "cardpay"
  = render "footer"

app/views/cards/create.html.haml
.wrapper
  = render "newheader"
  = render "card2"
  = render "footer"

app/views/cards/editpro.html.haml
.wrapper
  = render "newheader"
  = render "newmain"
  = render "items/sell"
  = render "footer"

app/views/cards/index2.html.haml
.container
  .content
    %section.content__chapter
      %h2.chapter__head 支払い方法
      .chapter__inner
        %section
          .chapter__inner__title
            %h3.chapter__inner__title__text クレジットカード一覧
        %section
          .chapter__inner__setting-card
            .chapter__inner__setting-card__content
              %i.far.fa-credit-card
              %p 　クレジットカードを追加する
        .setting-not-resist
          = link_to "#", class: ".setting-not-resist" do
            %span 支払い方法について
            %i.fas.fa-angle-right

app/views/cards/new.html.haml
.wrapper

= form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do


  .single-main.gray
    %h2.single-head-registration 支払い方法
    .single-content
      .form-group
      %label.bold カード番号
      %span.form-require 必須
      = text_field_tag "number", "", class: "number input-default", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
      %ul
        %li 
          =image_tag "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2482339763", size: "49x20",alt:"visa"
        %li 
          =image_tag "//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?2482339763", size: "34x20",alt:"master-card"
        %li 
          =image_tag "//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?2482339763", size: "30x20",alt:"saison-card"
        %li 
          =image_tag "//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?2482339763", size: "32x20",alt:"jcb"
        %li 
          =image_tag "//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?2482339763", size: "21x20",alt:"american_express"
        %li 
          =image_tag "//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?2482339763", size: "32x20",alt:"dinersclub"
        %li 
          =image_tag "//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?2482339763", size: "32x20",alt:"discover"
      .form-group
        %label.bold 有効期限
        %span.form-require 必須
        .select-wrap
          .select-wrap-half
            %select#exp_month{name: "exp_month", type: "text", class: "input-default"}
              %option{value: ""} --
              %option{value: "1"}01
              %option{value: "2"}02
              %option{value: "3"}03
              %option{value: "4"}04
              %option{value: "5"}05
              %option{value: "6"}06
              %option{value: "7"}07
              %option{value: "8"}08
              %option{value: "9"}09
              %option{value: "10"}10
              %option{value: "11"}11
              %option{value: "12"}12
            %i.fa.fa-angle-down
            %span
              月
          .select-wrap-half
            %select#exp_year{name: "exp_year", type: "text", class: "input-default"}
              %option{value: ""} --
              %option{value: "2020"}20
              %option{value: "2021"}21
              %option{value: "2022"}22
              %option{value: "2023"}23
              %option{value: "2024"}24
              %option{value: "2025"}25
              %option{value: "2026"}26
              %option{value: "2027"}27
              %option{value: "2028"}28
              %option{value: "2029"}29
            %i.fa.fa-angle-down
            %span
              年
      .form-group
        %label.bold セキュリティコード
        %span.form-require 必須
        = text_field_tag "cvc", "", class: "cvc input-default", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
        #card_token
        = submit_tag "追加する", id: "token_submit", class:"btn-red input-default"

app/views/cards/show.html.haml
.wrapper
  = render partial: 'header'
.container
  .chapter-container
    %section.content__chapter
      %h2.chapter__head 支払い方法
      .chapter__inner
        %section
          .chapter__inner__title
            %h3.chapter__inner__title__text クレジットカード一覧
          .chapter__inner__setting-card
            %ul.chapter__inner__setting-card__list
              %li
                = form_with url: delete_cards_path, method: :post, local: true, id: 'charge-form' do |f|
                  %figure
                    = image_tag "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2482339763", width: '26', height: '20', alt: @card_brand, id: "card_image"
                  .content__credit-cards__list--pay-num
                    = "**** **** **** " + @default_card_information.last4
                  .content__credit-cards__list--pay-num
                    - exp_month = @default_card_information.exp_month.to_s
                    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                    = exp_month + " / " + exp_year
                  %input{type: "hidden", name: "card_id", value: ""}
                  = f.submit "削除する", {class: "delete_btn"}
        .setting-not-resist
          = link_to "#", class: ".setting-not-resist" do
            %span 支払い方法について
            %i.fas.fa-angle-right
  = render partial: 'footer'