config/routes.rb
Rails.application.routes.draw do
  root "items#index"


  get 'purchase/index'
  get 'purchase/done'
  get 'cards/card'
  get 'home/show'
  get 'cards/editpro'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'telephones', to: 'users/registrations#new_telephones'
    post 'telephones', to: 'users/registrations#create_telephone'
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
    get 'users/signup' => 'users/registrations#new_sns', as:"new0_user_registration"
  end
  
  # omniauthのテスト用
  # get "auth/:provider" => "authentications#new", as: :new_authentication
  # get "auth/:provider/callback" => "authentications#create", as: :create_authentication


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'cards/index'
  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end
  
  resources :items do
    member do
      get 'buy'
      post 'buy_create'
      post 'pay'
      get 'done'
    end
    collection do
      get 'search'
    end
  end
  resources :brands, only: [:index, :new, :show]
  resources :categories, only:[:index]
  resources :images 

  resources :purchase, only: [:index] do
    collection do
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
    member do
      get 'index', to: 'purchase#index'
    end
    
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items

  validates :name, presence: true,exclusion: { in: %w(---) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @images = Image.find_by(params[:id])
    @category = Category.find(params[:id])
    @item = Item.find(params[:id])
  end
end

app/views/categories/index.html.haml
%body
  %header.buy-items__header
    = link_to root_path, class: "buy-items__header--logo" do
      = image_tag "fmarket_logo_red.svg", class: "buy-items__header--logo", alt:"logo"
  .buy-items__main
    .buy-items__main__text
      購入内容の確認
    .buy-items__main__item
      .buy-items__main__item--inner
        .buy-items__main__item--inner--box
          .buy-items__main__item--inner--box__left
          .buy-items__main__item--inner--box__right
            .buy-items__main__item--inner--box__right__name
              ¥ #{@item.name}
            .buy-items__main__item--inner--box__right__fee
              .buy-items__main__item--inner--box__right__fee__value
                ¥ #{@item.price}
              .buy-items__main__item--inner--box__right__fee__tax
                （税込）送料込み
    .buy-items__main__pay
      .buy-items__main__pay--inner
        .buy-items__main__pay--inner--box
          .buy-items__main__pay--inner--box__value
            .buy-items__main__pay--inner--box__value__left
              支払い金額
            .buy-items__main__pay--inner--box__value__right
              ¥7,000
          .buy-items__main__pay--inner--box__point
            .buy-items__main__pay--inner--box__point--box
              .buy-items__main__pay--inner--box__point--box__check
                %i.fas.fa-square
              .buy-items__main__pay--inner--box__point__box__text
                ポイントを使用 (所持ポイント: P0)
          .buy-items__main__pay--inner--box__way
            .buy-items__main__pay--inner--box__way--inner
              .buy-items-textTemplate
                .buy-items-textTemplate__left
                  支払い方法
                .buy-items-textTemplate__right
                  変更する
              .buy-items__main__pay--inner--box__way--inner__information
                .buy-items__main__pay--inner--box__way--inner__information__text
                  クレジットカード
                .buy-items__main__pay--inner--box__way--inner__information__int
                  ************1234
                .buy-items__main__pay--inner--box__way--inner__information__period
                  有効期限 11 / 11
              .buy-items__main__pay--inner--box__way--inner__bland
          .buy-items__main__pay--inner--box__adress
            .buy-items__main__pay--inner--box__adress--inner
              .buy-items-textTemplate
                .buy-items-textTemplate__left
                  配送先
                .buy-items-textTemplate__right
                  変更する
              .buy-items__main__pay--inner--box__adress--inner--information
                .buy-items__main__pay--inner--box__adress--inner--information__post
                  〒150-0041
                .buy-items__main__pay--inner--box__adress--inner--information__adress
                  東京都渋谷区神南１丁目１２−１６
                .buy-items__main__pay--inner--box__adress--inner--information__name
                  山本 太郎
          .buy-items__main__pay--inner--box__btn
          = link_to purchase_index_path, class: "buy-items__main__pay--inner--box__btn--red-btn" do
            .buy-items__main__pay--inner--box__btn--red-btn
              購入する
  %footer.buy-items__footer
    .buy-items__footer__list
      %ul.buy-items__footer__list--ul
        %li.buy-items__footer__list--ul--li プライバシーポリシー
        %li.buy-items__footer__list--ul--li メルカリ利用規約
        %li.buy-items__footer__list--ul--li 特定商取引に関する表記
    = link_to root_path, class: "buy-items__footer__logo" do
      = image_tag "logo_gray.svg", class: ".buy-items__footer__logo"
    .buy-items__footer__text
      © Mercari, Inc.